### ISSUE TITLE
egison 3.10.3 への対応

### ISSUE THREAD

**Issue by theoremoon** [greymd/egzact#17]
先日egison 3.10.3 がリリースされた (https://github.com/egison/egison/releases/tag/3.10.3) ようですが、これに伴ってegzactコマンド群の一部が壊れてしまっているようです。残念ながら私はegisonまるでわからないので、対応お願いします :pray:

```
$ egison --version
3.10.3
$ echo シェル芸 | dupl 2
Wrong number of arguments: ["partial"]: expected 1, but got 0
  stack trace: set-default-value, print-each-line, execution, main, <stdin>
```

**Comment by greymd** [comment]
ご連絡ありがとうございます。
こちら、下記のバージョンで修正しました。
https://github.com/greymd/egzact/releases/tag/v1.3.2

実は、最近Egisonはかなりアグレッシブに変更を加えておりまして。。
また近々動かなくなる懸念があります。
都度バージョンを更新するのも面倒だと思うので、バージョンを指定せずにダウンロードできるURLを用意しました。
https://git.io/egzact.deb
